[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
launchpad_program = "Ce46txc1VyJsFAamYciingPxyNd4Ux87jdcFvco1qieM"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"  
program = "dump/mpl_core.so"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "/home/renzo/.config/solana/id.json"



[scripts]
test = "yarn test"